server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  jwt:
    authkey: 9999
data:
  database:
    driver: mysql
    source: root:Hao@10086@tcp(8.155.62.49:3306)/ito?parseTime=True&loc=Local
  redis:
    addr: 8.155.62.49:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
