// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"ito-deposit/internal/basic/pkg"
	"ito-deposit/internal/biz"
	"ito-deposit/internal/conf"
	"ito-deposit/internal/data"
	"ito-deposit/internal/pkg/geo"
	"ito-deposit/internal/server"
	"ito-deposit/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	orderService := service.NewOrderService(dataData)
	userService := service.NewUserService(dataData, confServer)
	homeService := service.NewHomeService()
	sendSms, cleanup2, err := pkg.NewSendSms(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	depositService := service.NewDepositService(dataData, confServer, sendSms)
	adminRepo := data.NewAdminRepo(dataData, logger)
	adminUsecase := biz.NewAdminUsecase(adminRepo, logger)
	adminService := service.NewAdminService(dataData, confData, confServer, adminUsecase)
	cityRepo := data.NewCityRepo(dataData, logger)
	cityUsecase := biz.NewCityUsecase(cityRepo, logger)
	cityService := service.NewCityService(cityUsecase, logger)
	nearbyRepo := data.NewNearbyRepo(dataData, logger)
	geoService := geo.NewGeoService(confData)
	nearbyUsecase := biz.NewNearbyUsecase(nearbyRepo, geoService, cityUsecase, logger)
	nearbyService := service.NewNearbyService(nearbyUsecase, logger)
	groupService := service.NewGroupService(dataData)
	grpcServer := server.NewGRPCServer(confServer, greeterService, orderService, userService, homeService, depositService, adminService, cityService, nearbyService, groupService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, orderService, userService, homeService, depositService, adminService, cityService, nearbyService, groupService, logger)
	client, err := NewEtcdClient(confServer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	registrar := NewRegistrar(client)
	app := newApp(logger, grpcServer, httpServer, registrar, confServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
