// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: helloworld/v1/admin.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatePointRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePointRes) Reset() {
	*x = UpdatePointRes{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePointRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePointRes) ProtoMessage() {}

func (x *UpdatePointRes) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePointRes.ProtoReflect.Descriptor instead.
func (*UpdatePointRes) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatePointRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdatePointRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdatePointReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         *Point                 `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePointReq) Reset() {
	*x = UpdatePointReq{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePointReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePointReq) ProtoMessage() {}

func (x *UpdatePointReq) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePointReq.ProtoReflect.Descriptor instead.
func (*UpdatePointReq) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePointReq) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

type Point struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LocationId      int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address         string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	AvailableLarge  int32                  `protobuf:"varint,4,opt,name=available_large,json=availableLarge,proto3" json:"available_large,omitempty"`
	AvailableMedium int32                  `protobuf:"varint,5,opt,name=available_medium,json=availableMedium,proto3" json:"available_medium,omitempty"`
	AvailableSmall  int32                  `protobuf:"varint,6,opt,name=available_small,json=availableSmall,proto3" json:"available_small,omitempty"`
	OpenTime        string                 `protobuf:"bytes,7,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	Mobile          string                 `protobuf:"bytes,8,opt,name=mobile,proto3" json:"mobile,omitempty"`
	PointImage      string                 `protobuf:"bytes,9,opt,name=point_image,json=pointImage,proto3" json:"point_image,omitempty"`
	PointType       string                 `protobuf:"bytes,10,opt,name=point_type,json=pointType,proto3" json:"point_type,omitempty"`
	Latitude        float32                `protobuf:"fixed32,11,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude       float32                `protobuf:"fixed32,12,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Id              int32                  `protobuf:"varint,13,opt,name=id,proto3" json:"id,omitempty"`
	Status          string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *Point) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *Point) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Point) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Point) GetAvailableLarge() int32 {
	if x != nil {
		return x.AvailableLarge
	}
	return 0
}

func (x *Point) GetAvailableMedium() int32 {
	if x != nil {
		return x.AvailableMedium
	}
	return 0
}

func (x *Point) GetAvailableSmall() int32 {
	if x != nil {
		return x.AvailableSmall
	}
	return 0
}

func (x *Point) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *Point) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *Point) GetPointImage() string {
	if x != nil {
		return x.PointImage
	}
	return ""
}

func (x *Point) GetPointType() string {
	if x != nil {
		return x.PointType
	}
	return ""
}

func (x *Point) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Point) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Point) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Point) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AddPointReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LocationId      int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address         string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	AvailableLarge  int32                  `protobuf:"varint,4,opt,name=available_large,json=availableLarge,proto3" json:"available_large,omitempty"`
	AvailableMedium int32                  `protobuf:"varint,5,opt,name=available_medium,json=availableMedium,proto3" json:"available_medium,omitempty"`
	AvailableSmall  int32                  `protobuf:"varint,6,opt,name=available_small,json=availableSmall,proto3" json:"available_small,omitempty"`
	OpenTime        string                 `protobuf:"bytes,7,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	Mobile          string                 `protobuf:"bytes,8,opt,name=mobile,proto3" json:"mobile,omitempty"`
	PointImage      string                 `protobuf:"bytes,9,opt,name=point_image,json=pointImage,proto3" json:"point_image,omitempty"`
	PointType       string                 `protobuf:"bytes,10,opt,name=point_type,json=pointType,proto3" json:"point_type,omitempty"`
	Latitude        float32                `protobuf:"fixed32,11,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude       float32                `protobuf:"fixed32,12,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddPointReq) Reset() {
	*x = AddPointReq{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPointReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPointReq) ProtoMessage() {}

func (x *AddPointReq) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPointReq.ProtoReflect.Descriptor instead.
func (*AddPointReq) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AddPointReq) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *AddPointReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddPointReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddPointReq) GetAvailableLarge() int32 {
	if x != nil {
		return x.AvailableLarge
	}
	return 0
}

func (x *AddPointReq) GetAvailableMedium() int32 {
	if x != nil {
		return x.AvailableMedium
	}
	return 0
}

func (x *AddPointReq) GetAvailableSmall() int32 {
	if x != nil {
		return x.AvailableSmall
	}
	return 0
}

func (x *AddPointReq) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *AddPointReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AddPointReq) GetPointImage() string {
	if x != nil {
		return x.PointImage
	}
	return ""
}

func (x *AddPointReq) GetPointType() string {
	if x != nil {
		return x.PointType
	}
	return ""
}

func (x *AddPointReq) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AddPointReq) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type AddPointRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPointRes) Reset() {
	*x = AddPointRes{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPointRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPointRes) ProtoMessage() {}

func (x *AddPointRes) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPointRes.ProtoReflect.Descriptor instead.
func (*AddPointRes) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AddPointRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddPointRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UploadFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          []byte                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileReq) Reset() {
	*x = UploadFileReq{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileReq) ProtoMessage() {}

func (x *UploadFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileReq.ProtoReflect.Descriptor instead.
func (*UploadFileReq) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *UploadFileReq) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *UploadFileReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadFileReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type UploadFileRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRes) Reset() {
	*x = UploadFileRes{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRes) ProtoMessage() {}

func (x *UploadFileRes) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRes.ProtoReflect.Descriptor instead.
func (*UploadFileRes) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *UploadFileRes) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AdminLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	SmsCode       string                 `protobuf:"bytes,3,opt,name=smsCode,proto3" json:"smsCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginReq) Reset() {
	*x = AdminLoginReq{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginReq) ProtoMessage() {}

func (x *AdminLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginReq.ProtoReflect.Descriptor instead.
func (*AdminLoginReq) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *AdminLoginReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AdminLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AdminLoginReq) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

type AdminLoginRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginRes) Reset() {
	*x = AdminLoginRes{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginRes) ProtoMessage() {}

func (x *AdminLoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginRes.ProtoReflect.Descriptor instead.
func (*AdminLoginRes) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *AdminLoginRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminLoginRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AdminLoginRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminLoginRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SetPriceRuleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     int64                  `protobuf:"varint,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Rules         []*LockerPriceRule     `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPriceRuleReq) Reset() {
	*x = SetPriceRuleReq{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPriceRuleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPriceRuleReq) ProtoMessage() {}

func (x *SetPriceRuleReq) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPriceRuleReq.ProtoReflect.Descriptor instead.
func (*SetPriceRuleReq) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *SetPriceRuleReq) GetNetworkId() int64 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *SetPriceRuleReq) GetRules() []*LockerPriceRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type SetPriceRuleRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPriceRuleRes) Reset() {
	*x = SetPriceRuleRes{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPriceRuleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPriceRuleRes) ProtoMessage() {}

func (x *SetPriceRuleRes) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPriceRuleRes.ProtoReflect.Descriptor instead.
func (*SetPriceRuleRes) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *SetPriceRuleRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SetPriceRuleRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetPriceRuleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     int64                  `protobuf:"varint,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceRuleReq) Reset() {
	*x = GetPriceRuleReq{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceRuleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceRuleReq) ProtoMessage() {}

func (x *GetPriceRuleReq) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceRuleReq.ProtoReflect.Descriptor instead.
func (*GetPriceRuleReq) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *GetPriceRuleReq) GetNetworkId() int64 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

type GetPriceRuleRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*LockerPriceRule     `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceRuleRes) Reset() {
	*x = GetPriceRuleRes{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceRuleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceRuleRes) ProtoMessage() {}

func (x *GetPriceRuleRes) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceRuleRes.ProtoReflect.Descriptor instead.
func (*GetPriceRuleRes) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *GetPriceRuleRes) GetRules() []*LockerPriceRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type LockerPriceRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础标识
	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                            // 规则ID（更新时使用）
	RuleName string `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"` // 规则名称（可选）
	// 核心配置
	FeeType      int32   `protobuf:"varint,3,opt,name=fee_type,json=feeType,proto3" json:"fee_type,omitempty"`                 // 1-计时 2-按日
	LockerType   int32   `protobuf:"varint,4,opt,name=locker_type,json=lockerType,proto3" json:"locker_type,omitempty"`        // 1-小柜 2-大柜
	FreeDuration float32 `protobuf:"fixed32,5,opt,name=free_duration,json=freeDuration,proto3" json:"free_duration,omitempty"` // 免费时长(小时)
	// 金额设置
	HourlyRate    float32 `protobuf:"fixed32,6,opt,name=hourly_rate,json=hourlyRate,proto3" json:"hourly_rate,omitempty"`           // 小时费率
	DailyCap      float32 `protobuf:"fixed32,7,opt,name=daily_cap,json=dailyCap,proto3" json:"daily_cap,omitempty"`                 // 24小时封顶
	DailyRate     float32 `protobuf:"fixed32,8,opt,name=daily_rate,json=dailyRate,proto3" json:"daily_rate,omitempty"`              // 日费率
	AdvanceAmount float32 `protobuf:"fixed32,9,opt,name=advance_amount,json=advanceAmount,proto3" json:"advance_amount,omitempty"`  // 预付金额
	DepositAmount float32 `protobuf:"fixed32,10,opt,name=deposit_amount,json=depositAmount,proto3" json:"deposit_amount,omitempty"` // 押金金额
	// 功能开关
	IsDepositEnabled bool `protobuf:"varint,11,opt,name=is_deposit_enabled,json=isDepositEnabled,proto3" json:"is_deposit_enabled,omitempty"`
	IsAdvancePay     bool `protobuf:"varint,12,opt,name=is_advance_pay,json=isAdvancePay,proto3" json:"is_advance_pay,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LockerPriceRule) Reset() {
	*x = LockerPriceRule{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockerPriceRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockerPriceRule) ProtoMessage() {}

func (x *LockerPriceRule) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockerPriceRule.ProtoReflect.Descriptor instead.
func (*LockerPriceRule) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *LockerPriceRule) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LockerPriceRule) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *LockerPriceRule) GetFeeType() int32 {
	if x != nil {
		return x.FeeType
	}
	return 0
}

func (x *LockerPriceRule) GetLockerType() int32 {
	if x != nil {
		return x.LockerType
	}
	return 0
}

func (x *LockerPriceRule) GetFreeDuration() float32 {
	if x != nil {
		return x.FreeDuration
	}
	return 0
}

func (x *LockerPriceRule) GetHourlyRate() float32 {
	if x != nil {
		return x.HourlyRate
	}
	return 0
}

func (x *LockerPriceRule) GetDailyCap() float32 {
	if x != nil {
		return x.DailyCap
	}
	return 0
}

func (x *LockerPriceRule) GetDailyRate() float32 {
	if x != nil {
		return x.DailyRate
	}
	return 0
}

func (x *LockerPriceRule) GetAdvanceAmount() float32 {
	if x != nil {
		return x.AdvanceAmount
	}
	return 0
}

func (x *LockerPriceRule) GetDepositAmount() float32 {
	if x != nil {
		return x.DepositAmount
	}
	return 0
}

func (x *LockerPriceRule) GetIsDepositEnabled() bool {
	if x != nil {
		return x.IsDepositEnabled
	}
	return false
}

func (x *LockerPriceRule) GetIsAdvancePay() bool {
	if x != nil {
		return x.IsAdvancePay
	}
	return false
}

type PointListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointListReq) Reset() {
	*x = PointListReq{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointListReq) ProtoMessage() {}

func (x *PointListReq) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointListReq.ProtoReflect.Descriptor instead.
func (*PointListReq) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{14}
}

type PointListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	List          []*PointList           `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointListRes) Reset() {
	*x = PointListRes{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointListRes) ProtoMessage() {}

func (x *PointListRes) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointListRes.ProtoReflect.Descriptor instead.
func (*PointListRes) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *PointListRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PointListRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PointListRes) GetList() []*PointList {
	if x != nil {
		return x.List
	}
	return nil
}

type PointList struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address         string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	AvailableLarge  int64                  `protobuf:"varint,3,opt,name=available_large,json=availableLarge,proto3" json:"available_large,omitempty"`
	AvailableMedium int64                  `protobuf:"varint,4,opt,name=available_medium,json=availableMedium,proto3" json:"available_medium,omitempty"`
	AvailableSmall  int64                  `protobuf:"varint,5,opt,name=available_small,json=availableSmall,proto3" json:"available_small,omitempty"`
	Id              int64                  `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PointList) Reset() {
	*x = PointList{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointList) ProtoMessage() {}

func (x *PointList) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointList.ProtoReflect.Descriptor instead.
func (*PointList) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *PointList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PointList) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PointList) GetAvailableLarge() int64 {
	if x != nil {
		return x.AvailableLarge
	}
	return 0
}

func (x *PointList) GetAvailableMedium() int64 {
	if x != nil {
		return x.AvailableMedium
	}
	return 0
}

func (x *PointList) GetAvailableSmall() int64 {
	if x != nil {
		return x.AvailableSmall
	}
	return 0
}

func (x *PointList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PointInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointInfoReq) Reset() {
	*x = PointInfoReq{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointInfoReq) ProtoMessage() {}

func (x *PointInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointInfoReq.ProtoReflect.Descriptor instead.
func (*PointInfoReq) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *PointInfoReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PointInfoRes struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg             string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address         string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PointType       string                 `protobuf:"bytes,5,opt,name=point_type,json=pointType,proto3" json:"point_type,omitempty"`
	AvailableLarge  int64                  `protobuf:"varint,6,opt,name=available_large,json=availableLarge,proto3" json:"available_large,omitempty"`
	AvailableMedium int64                  `protobuf:"varint,7,opt,name=available_medium,json=availableMedium,proto3" json:"available_medium,omitempty"`
	AvailableSmall  int64                  `protobuf:"varint,8,opt,name=available_small,json=availableSmall,proto3" json:"available_small,omitempty"`
	OpenTime        string                 `protobuf:"bytes,9,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	Staus           string                 `protobuf:"bytes,10,opt,name=staus,proto3" json:"staus,omitempty"`
	PointImage      string                 `protobuf:"bytes,11,opt,name=point_image,json=pointImage,proto3" json:"point_image,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PointInfoRes) Reset() {
	*x = PointInfoRes{}
	mi := &file_helloworld_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointInfoRes) ProtoMessage() {}

func (x *PointInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointInfoRes.ProtoReflect.Descriptor instead.
func (*PointInfoRes) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *PointInfoRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PointInfoRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PointInfoRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PointInfoRes) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PointInfoRes) GetPointType() string {
	if x != nil {
		return x.PointType
	}
	return ""
}

func (x *PointInfoRes) GetAvailableLarge() int64 {
	if x != nil {
		return x.AvailableLarge
	}
	return 0
}

func (x *PointInfoRes) GetAvailableMedium() int64 {
	if x != nil {
		return x.AvailableMedium
	}
	return 0
}

func (x *PointInfoRes) GetAvailableSmall() int64 {
	if x != nil {
		return x.AvailableSmall
	}
	return 0
}

func (x *PointInfoRes) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *PointInfoRes) GetStaus() string {
	if x != nil {
		return x.Staus
	}
	return ""
}

func (x *PointInfoRes) GetPointImage() string {
	if x != nil {
		return x.PointImage
	}
	return ""
}

var File_helloworld_v1_admin_proto protoreflect.FileDescriptor

const file_helloworld_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x19helloworld/v1/admin.proto\x12\x11api.helloworld.v1\x1a\x1cgoogle/api/annotations.proto\"6\n" +
	"\x0eUpdatePointRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"@\n" +
	"\x0eUpdatePointReq\x12.\n" +
	"\x05point\x18\x02 \x01(\v2\x18.api.helloworld.v1.PointR\x05point\"\xaa\x03\n" +
	"\x05Point\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12'\n" +
	"\x0favailable_large\x18\x04 \x01(\x05R\x0eavailableLarge\x12)\n" +
	"\x10available_medium\x18\x05 \x01(\x05R\x0favailableMedium\x12'\n" +
	"\x0favailable_small\x18\x06 \x01(\x05R\x0eavailableSmall\x12\x1b\n" +
	"\topen_time\x18\a \x01(\tR\bopenTime\x12\x16\n" +
	"\x06mobile\x18\b \x01(\tR\x06mobile\x12\x1f\n" +
	"\vpoint_image\x18\t \x01(\tR\n" +
	"pointImage\x12\x1d\n" +
	"\n" +
	"point_type\x18\n" +
	" \x01(\tR\tpointType\x12\x1a\n" +
	"\blatitude\x18\v \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\f \x01(\x02R\tlongitude\x12\x0e\n" +
	"\x02id\x18\r \x01(\x05R\x02id\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\"\x88\x03\n" +
	"\vAddPointReq\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12'\n" +
	"\x0favailable_large\x18\x04 \x01(\x05R\x0eavailableLarge\x12)\n" +
	"\x10available_medium\x18\x05 \x01(\x05R\x0favailableMedium\x12'\n" +
	"\x0favailable_small\x18\x06 \x01(\x05R\x0eavailableSmall\x12\x1b\n" +
	"\topen_time\x18\a \x01(\tR\bopenTime\x12\x16\n" +
	"\x06mobile\x18\b \x01(\tR\x06mobile\x12\x1f\n" +
	"\vpoint_image\x18\t \x01(\tR\n" +
	"pointImage\x12\x1d\n" +
	"\n" +
	"point_type\x18\n" +
	" \x01(\tR\tpointType\x12\x1a\n" +
	"\blatitude\x18\v \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\f \x01(\x02R\tlongitude\"3\n" +
	"\vAddPointRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"[\n" +
	"\rUploadFileReq\x12\x12\n" +
	"\x04file\x18\x01 \x01(\fR\x04file\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\x12\x1a\n" +
	"\bfileSize\x18\x03 \x01(\x03R\bfileSize\"!\n" +
	"\rUploadFileRes\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"]\n" +
	"\rAdminLoginReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x18\n" +
	"\asmsCode\x18\x03 \x01(\tR\asmsCode\"[\n" +
	"\rAdminLoginRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"j\n" +
	"\x0fSetPriceRuleReq\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\x03R\tnetworkId\x128\n" +
	"\x05rules\x18\x02 \x03(\v2\".api.helloworld.v1.LockerPriceRuleR\x05rules\"7\n" +
	"\x0fSetPriceRuleRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"0\n" +
	"\x0fGetPriceRuleReq\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\x03R\tnetworkId\"K\n" +
	"\x0fGetPriceRuleRes\x128\n" +
	"\x05rules\x18\x01 \x03(\v2\".api.helloworld.v1.LockerPriceRuleR\x05rules\"\x9e\x03\n" +
	"\x0fLockerPriceRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\trule_name\x18\x02 \x01(\tR\bruleName\x12\x19\n" +
	"\bfee_type\x18\x03 \x01(\x05R\afeeType\x12\x1f\n" +
	"\vlocker_type\x18\x04 \x01(\x05R\n" +
	"lockerType\x12#\n" +
	"\rfree_duration\x18\x05 \x01(\x02R\ffreeDuration\x12\x1f\n" +
	"\vhourly_rate\x18\x06 \x01(\x02R\n" +
	"hourlyRate\x12\x1b\n" +
	"\tdaily_cap\x18\a \x01(\x02R\bdailyCap\x12\x1d\n" +
	"\n" +
	"daily_rate\x18\b \x01(\x02R\tdailyRate\x12%\n" +
	"\x0eadvance_amount\x18\t \x01(\x02R\radvanceAmount\x12%\n" +
	"\x0edeposit_amount\x18\n" +
	" \x01(\x02R\rdepositAmount\x12,\n" +
	"\x12is_deposit_enabled\x18\v \x01(\bR\x10isDepositEnabled\x12$\n" +
	"\x0eis_advance_pay\x18\f \x01(\bR\fisAdvancePay\"\x0e\n" +
	"\fPointListReq\"f\n" +
	"\fPointListRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x120\n" +
	"\x04list\x18\x03 \x03(\v2\x1c.api.helloworld.v1.PointListR\x04list\"\xc6\x01\n" +
	"\tPointList\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12'\n" +
	"\x0favailable_large\x18\x03 \x01(\x03R\x0eavailableLarge\x12)\n" +
	"\x10available_medium\x18\x04 \x01(\x03R\x0favailableMedium\x12'\n" +
	"\x0favailable_small\x18\x05 \x01(\x03R\x0eavailableSmall\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\x03R\x02id\"\x1e\n" +
	"\fPointInfoReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xd2\x02\n" +
	"\fPointInfoRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"point_type\x18\x05 \x01(\tR\tpointType\x12'\n" +
	"\x0favailable_large\x18\x06 \x01(\x03R\x0eavailableLarge\x12)\n" +
	"\x10available_medium\x18\a \x01(\x03R\x0favailableMedium\x12'\n" +
	"\x0favailable_small\x18\b \x01(\x03R\x0eavailableSmall\x12\x1b\n" +
	"\topen_time\x18\t \x01(\tR\bopenTime\x12\x14\n" +
	"\x05staus\x18\n" +
	" \x01(\tR\x05staus\x12\x1f\n" +
	"\vpoint_image\x18\v \x01(\tR\n" +
	"pointImage2\xf3\x06\n" +
	"\x05Admin\x12e\n" +
	"\tPointInfo\x12\x1f.api.helloworld.v1.PointInfoReq\x1a\x1f.api.helloworld.v1.PointInfoRes\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/point_info\x12b\n" +
	"\tPointList\x12\x1f.api.helloworld.v1.PointListReq\x1a\x1f.api.helloworld.v1.PointListRes\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/point_list\x12i\n" +
	"\n" +
	"AdminLogin\x12 .api.helloworld.v1.AdminLoginReq\x1a .api.helloworld.v1.AdminLoginRes\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/admin_login\x12v\n" +
	"\fSetPriceRule\x12\".api.helloworld.v1.SetPriceRuleReq\x1a\".api.helloworld.v1.SetPriceRuleRes\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/admin/setPriceRule\x12s\n" +
	"\fGetPriceRule\x12\".api.helloworld.v1.GetPriceRuleReq\x1a\".api.helloworld.v1.GetPriceRuleRes\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/admin/getPriceRule\x12k\n" +
	"\n" +
	"UploadFile\x12 .api.helloworld.v1.UploadFileReq\x1a .api.helloworld.v1.UploadFileRes\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/admin/uploadFile\x12f\n" +
	"\bAddPoint\x12\x1e.api.helloworld.v1.AddPointReq\x1a\x1e.api.helloworld.v1.AddPointRes\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/admin/addPoint\x12r\n" +
	"\vUpdatePoint\x12!.api.helloworld.v1.UpdatePointReq\x1a!.api.helloworld.v1.UpdatePointRes\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/admin/updatePointB7\n" +
	"\x11api.helloworld.v1P\x01Z ito-deposit/api/helloworld/v1;v1b\x06proto3"

var (
	file_helloworld_v1_admin_proto_rawDescOnce sync.Once
	file_helloworld_v1_admin_proto_rawDescData []byte
)

func file_helloworld_v1_admin_proto_rawDescGZIP() []byte {
	file_helloworld_v1_admin_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_admin_proto_rawDesc), len(file_helloworld_v1_admin_proto_rawDesc)))
	})
	return file_helloworld_v1_admin_proto_rawDescData
}

var file_helloworld_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_helloworld_v1_admin_proto_goTypes = []any{
	(*UpdatePointRes)(nil),  // 0: api.helloworld.v1.UpdatePointRes
	(*UpdatePointReq)(nil),  // 1: api.helloworld.v1.UpdatePointReq
	(*Point)(nil),           // 2: api.helloworld.v1.Point
	(*AddPointReq)(nil),     // 3: api.helloworld.v1.AddPointReq
	(*AddPointRes)(nil),     // 4: api.helloworld.v1.AddPointRes
	(*UploadFileReq)(nil),   // 5: api.helloworld.v1.UploadFileReq
	(*UploadFileRes)(nil),   // 6: api.helloworld.v1.UploadFileRes
	(*AdminLoginReq)(nil),   // 7: api.helloworld.v1.AdminLoginReq
	(*AdminLoginRes)(nil),   // 8: api.helloworld.v1.AdminLoginRes
	(*SetPriceRuleReq)(nil), // 9: api.helloworld.v1.SetPriceRuleReq
	(*SetPriceRuleRes)(nil), // 10: api.helloworld.v1.SetPriceRuleRes
	(*GetPriceRuleReq)(nil), // 11: api.helloworld.v1.GetPriceRuleReq
	(*GetPriceRuleRes)(nil), // 12: api.helloworld.v1.GetPriceRuleRes
	(*LockerPriceRule)(nil), // 13: api.helloworld.v1.LockerPriceRule
	(*PointListReq)(nil),    // 14: api.helloworld.v1.PointListReq
	(*PointListRes)(nil),    // 15: api.helloworld.v1.PointListRes
	(*PointList)(nil),       // 16: api.helloworld.v1.PointList
	(*PointInfoReq)(nil),    // 17: api.helloworld.v1.PointInfoReq
	(*PointInfoRes)(nil),    // 18: api.helloworld.v1.PointInfoRes
}
var file_helloworld_v1_admin_proto_depIdxs = []int32{
	2,  // 0: api.helloworld.v1.UpdatePointReq.point:type_name -> api.helloworld.v1.Point
	13, // 1: api.helloworld.v1.SetPriceRuleReq.rules:type_name -> api.helloworld.v1.LockerPriceRule
	13, // 2: api.helloworld.v1.GetPriceRuleRes.rules:type_name -> api.helloworld.v1.LockerPriceRule
	16, // 3: api.helloworld.v1.PointListRes.list:type_name -> api.helloworld.v1.PointList
	17, // 4: api.helloworld.v1.Admin.PointInfo:input_type -> api.helloworld.v1.PointInfoReq
	14, // 5: api.helloworld.v1.Admin.PointList:input_type -> api.helloworld.v1.PointListReq
	7,  // 6: api.helloworld.v1.Admin.AdminLogin:input_type -> api.helloworld.v1.AdminLoginReq
	9,  // 7: api.helloworld.v1.Admin.SetPriceRule:input_type -> api.helloworld.v1.SetPriceRuleReq
	11, // 8: api.helloworld.v1.Admin.GetPriceRule:input_type -> api.helloworld.v1.GetPriceRuleReq
	5,  // 9: api.helloworld.v1.Admin.UploadFile:input_type -> api.helloworld.v1.UploadFileReq
	3,  // 10: api.helloworld.v1.Admin.AddPoint:input_type -> api.helloworld.v1.AddPointReq
	1,  // 11: api.helloworld.v1.Admin.UpdatePoint:input_type -> api.helloworld.v1.UpdatePointReq
	18, // 12: api.helloworld.v1.Admin.PointInfo:output_type -> api.helloworld.v1.PointInfoRes
	15, // 13: api.helloworld.v1.Admin.PointList:output_type -> api.helloworld.v1.PointListRes
	8,  // 14: api.helloworld.v1.Admin.AdminLogin:output_type -> api.helloworld.v1.AdminLoginRes
	10, // 15: api.helloworld.v1.Admin.SetPriceRule:output_type -> api.helloworld.v1.SetPriceRuleRes
	12, // 16: api.helloworld.v1.Admin.GetPriceRule:output_type -> api.helloworld.v1.GetPriceRuleRes
	6,  // 17: api.helloworld.v1.Admin.UploadFile:output_type -> api.helloworld.v1.UploadFileRes
	4,  // 18: api.helloworld.v1.Admin.AddPoint:output_type -> api.helloworld.v1.AddPointRes
	0,  // 19: api.helloworld.v1.Admin.UpdatePoint:output_type -> api.helloworld.v1.UpdatePointRes
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_helloworld_v1_admin_proto_init() }
func file_helloworld_v1_admin_proto_init() {
	if File_helloworld_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_admin_proto_rawDesc), len(file_helloworld_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_admin_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_admin_proto_depIdxs,
		MessageInfos:      file_helloworld_v1_admin_proto_msgTypes,
	}.Build()
	File_helloworld_v1_admin_proto = out.File
	file_helloworld_v1_admin_proto_goTypes = nil
	file_helloworld_v1_admin_proto_depIdxs = nil
}
