// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.26.1
// source: api/helloworld/v1/deposit.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDepositListDeposit = "/api.helloworld.v1.Deposit/ListDeposit"

type DepositHTTPServer interface {
	ListDeposit(context.Context, *ListDepositRequest) (*ListDepositReply, error)
}

func RegisterDepositHTTPServer(s *http.Server, srv DepositHTTPServer) {
	r := s.Route("/")
	r.GET("/deposit", _Deposit_ListDeposit0_HTTP_Handler(srv))
}

func _Deposit_ListDeposit0_HTTP_Handler(srv DepositHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDepositRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepositListDeposit)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDeposit(ctx, req.(*ListDepositRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDepositReply)
		return ctx.Result(200, reply)
	}
}

type DepositHTTPClient interface {
	ListDeposit(ctx context.Context, req *ListDepositRequest, opts ...http.CallOption) (rsp *ListDepositReply, err error)
}

type DepositHTTPClientImpl struct {
	cc *http.Client
}

func NewDepositHTTPClient(client *http.Client) DepositHTTPClient {
	return &DepositHTTPClientImpl{client}
}

func (c *DepositHTTPClientImpl) ListDeposit(ctx context.Context, in *ListDepositRequest, opts ...http.CallOption) (*ListDepositReply, error) {
	var out ListDepositReply
	pattern := "/deposit"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDepositListDeposit))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
