// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.31.1
// source: api/helloworld/v1/home.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHomeCreateLocal = "/api.helloworld.v1.Home/CreateLocal"
const OperationHomeListHome = "/api.helloworld.v1.Home/ListHome"

type HomeHTTPServer interface {
	CreateLocal(context.Context, *CreateLocalRequest) (*CreateLocalReply, error)
	ListHome(context.Context, *ListHomeRequest) (*ListHomeReply, error)
}

func RegisterHomeHTTPServer(s *http.Server, srv HomeHTTPServer) {
	r := s.Route("/")
	r.GET("/home", _Home_ListHome0_HTTP_Handler(srv))
	r.GET("/home/local", _Home_CreateLocal0_HTTP_Handler(srv))
}

func _Home_ListHome0_HTTP_Handler(srv HomeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListHomeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHomeListHome)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListHome(ctx, req.(*ListHomeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListHomeReply)
		return ctx.Result(200, reply)
	}
}

func _Home_CreateLocal0_HTTP_Handler(srv HomeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateLocalRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHomeCreateLocal)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateLocal(ctx, req.(*CreateLocalRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateLocalReply)
		return ctx.Result(200, reply)
	}
}

type HomeHTTPClient interface {
	CreateLocal(ctx context.Context, req *CreateLocalRequest, opts ...http.CallOption) (rsp *CreateLocalReply, err error)
	ListHome(ctx context.Context, req *ListHomeRequest, opts ...http.CallOption) (rsp *ListHomeReply, err error)
}

type HomeHTTPClientImpl struct {
	cc *http.Client
}

func NewHomeHTTPClient(client *http.Client) HomeHTTPClient {
	return &HomeHTTPClientImpl{client}
}

func (c *HomeHTTPClientImpl) CreateLocal(ctx context.Context, in *CreateLocalRequest, opts ...http.CallOption) (*CreateLocalReply, error) {
	var out CreateLocalReply
	pattern := "/home/local"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHomeCreateLocal))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HomeHTTPClientImpl) ListHome(ctx context.Context, in *ListHomeRequest, opts ...http.CallOption) (*ListHomeReply, error) {
	var out ListHomeReply
	pattern := "/home"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHomeListHome))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
