// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/helloworld/v1/order.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManageOrderDetailRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderId           int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`          // 订单ID（必填，关联主订单）
	CabinetId         int64                  `protobuf:"varint,2,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`    // 柜子ID（必填，寄存的柜格编号）
	UserId            int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户ID（必填，寄存人ID）
	ExpireTime        int64                  `protobuf:"varint,4,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 过期时间（必填，秒级时间戳）
	Status            int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                           // 寄存状态（必填，1=寄存中，0=待寄存）
	Id                int64                  `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	OrderNumber       int64                  `protobuf:"varint,7,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	ScheduledDuration int64                  `protobuf:"varint,8,opt,name=scheduled_duration,json=scheduledDuration,proto3" json:"scheduled_duration,omitempty"`
	HourlyRate        int64                  `protobuf:"varint,9,opt,name=hourly_rate,json=hourlyRate,proto3" json:"hourly_rate,omitempty"`
	Role              int64                  `protobuf:"varint,10,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ManageOrderDetailRequest) Reset() {
	*x = ManageOrderDetailRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageOrderDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageOrderDetailRequest) ProtoMessage() {}

func (x *ManageOrderDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageOrderDetailRequest.ProtoReflect.Descriptor instead.
func (*ManageOrderDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *ManageOrderDetailRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ManageOrderDetailRequest) GetCabinetId() int64 {
	if x != nil {
		return x.CabinetId
	}
	return 0
}

func (x *ManageOrderDetailRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ManageOrderDetailRequest) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *ManageOrderDetailRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ManageOrderDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ManageOrderDetailRequest) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *ManageOrderDetailRequest) GetScheduledDuration() int64 {
	if x != nil {
		return x.ScheduledDuration
	}
	return 0
}

func (x *ManageOrderDetailRequest) GetHourlyRate() int64 {
	if x != nil {
		return x.HourlyRate
	}
	return 0
}

func (x *ManageOrderDetailRequest) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

type ManageOrderDetailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Order         []*OrderInfo           `protobuf:"bytes,1,rep,name=order,proto3" json:"order,omitempty"` // 返回单个订单信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageOrderDetailReply) Reset() {
	*x = ManageOrderDetailReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageOrderDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageOrderDetailReply) ProtoMessage() {}

func (x *ManageOrderDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageOrderDetailReply.ProtoReflect.Descriptor instead.
func (*ManageOrderDetailReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *ManageOrderDetailReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ManageOrderDetailReply) GetOrder() []*OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

type ManageOrderDelRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderId           int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`          // 订单ID（必填，关联主订单）
	CabinetId         int64                  `protobuf:"varint,2,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`    // 柜子ID（必填，寄存的柜格编号）
	UserId            int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户ID（必填，寄存人ID）
	ExpireTime        int64                  `protobuf:"varint,4,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 过期时间（必填，秒级时间戳）
	Status            int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                           // 寄存状态（必填，1=寄存中，0=待寄存）
	Id                int64                  `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	OrderNumber       int64                  `protobuf:"varint,7,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	ScheduledDuration int64                  `protobuf:"varint,8,opt,name=scheduled_duration,json=scheduledDuration,proto3" json:"scheduled_duration,omitempty"`
	HourlyRate        int64                  `protobuf:"varint,9,opt,name=hourly_rate,json=hourlyRate,proto3" json:"hourly_rate,omitempty"`
	Role              int64                  `protobuf:"varint,10,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ManageOrderDelRequest) Reset() {
	*x = ManageOrderDelRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageOrderDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageOrderDelRequest) ProtoMessage() {}

func (x *ManageOrderDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageOrderDelRequest.ProtoReflect.Descriptor instead.
func (*ManageOrderDelRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *ManageOrderDelRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ManageOrderDelRequest) GetCabinetId() int64 {
	if x != nil {
		return x.CabinetId
	}
	return 0
}

func (x *ManageOrderDelRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ManageOrderDelRequest) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *ManageOrderDelRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ManageOrderDelRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ManageOrderDelRequest) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *ManageOrderDelRequest) GetScheduledDuration() int64 {
	if x != nil {
		return x.ScheduledDuration
	}
	return 0
}

func (x *ManageOrderDelRequest) GetHourlyRate() int64 {
	if x != nil {
		return x.HourlyRate
	}
	return 0
}

func (x *ManageOrderDelRequest) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

type ManageOrderDelReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageOrderDelReply) Reset() {
	*x = ManageOrderDelReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageOrderDelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageOrderDelReply) ProtoMessage() {}

func (x *ManageOrderDelReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageOrderDelReply.ProtoReflect.Descriptor instead.
func (*ManageOrderDelReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *ManageOrderDelReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type HandleTimeOutTaskRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderId           int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`          // 订单ID（必填，关联主订单）
	CabinetId         int64                  `protobuf:"varint,2,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`    // 柜子ID（必填，寄存的柜格编号）
	UserId            int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户ID（必填，寄存人ID）
	ExpireTime        int64                  `protobuf:"varint,4,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 过期时间（必填，秒级时间戳）
	Status            int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                           // 寄存状态（必填，1=寄存中，0=待寄存）
	Id                int64                  `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	OrderNumber       int64                  `protobuf:"varint,7,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	ScheduledDuration int64                  `protobuf:"varint,8,opt,name=scheduled_duration,json=scheduledDuration,proto3" json:"scheduled_duration,omitempty"`
	HourlyRate        int64                  `protobuf:"varint,9,opt,name=hourly_rate,json=hourlyRate,proto3" json:"hourly_rate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HandleTimeOutTaskRequest) Reset() {
	*x = HandleTimeOutTaskRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleTimeOutTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleTimeOutTaskRequest) ProtoMessage() {}

func (x *HandleTimeOutTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleTimeOutTaskRequest.ProtoReflect.Descriptor instead.
func (*HandleTimeOutTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *HandleTimeOutTaskRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *HandleTimeOutTaskRequest) GetCabinetId() int64 {
	if x != nil {
		return x.CabinetId
	}
	return 0
}

func (x *HandleTimeOutTaskRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HandleTimeOutTaskRequest) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *HandleTimeOutTaskRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HandleTimeOutTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HandleTimeOutTaskRequest) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *HandleTimeOutTaskRequest) GetScheduledDuration() int64 {
	if x != nil {
		return x.ScheduledDuration
	}
	return 0
}

func (x *HandleTimeOutTaskRequest) GetHourlyRate() int64 {
	if x != nil {
		return x.HourlyRate
	}
	return 0
}

type HandleTimeOutTaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleTimeOutTaskReply) Reset() {
	*x = HandleTimeOutTaskReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleTimeOutTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleTimeOutTaskReply) ProtoMessage() {}

func (x *HandleTimeOutTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleTimeOutTaskReply.ProtoReflect.Descriptor instead.
func (*HandleTimeOutTaskReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *HandleTimeOutTaskReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type HandleRemindTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`          // 订单ID（必填，关联主订单）
	CabinetId     int64                  `protobuf:"varint,2,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`    // 柜子ID（必填，寄存的柜格编号）
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户ID（必填，寄存人ID）
	ExpireTime    int64                  `protobuf:"varint,4,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 过期时间（必填，秒级时间戳）
	Status        int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                           // 寄存状态（必填，1=寄存中，0=待寄存）
	Id            int64                  `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	OrderNumber   int64                  `protobuf:"varint,7,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleRemindTaskRequest) Reset() {
	*x = HandleRemindTaskRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleRemindTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleRemindTaskRequest) ProtoMessage() {}

func (x *HandleRemindTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleRemindTaskRequest.ProtoReflect.Descriptor instead.
func (*HandleRemindTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *HandleRemindTaskRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *HandleRemindTaskRequest) GetCabinetId() int64 {
	if x != nil {
		return x.CabinetId
	}
	return 0
}

func (x *HandleRemindTaskRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HandleRemindTaskRequest) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *HandleRemindTaskRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HandleRemindTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HandleRemindTaskRequest) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

type HandleRemindTaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleRemindTaskReply) Reset() {
	*x = HandleRemindTaskReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleRemindTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleRemindTaskReply) ProtoMessage() {}

func (x *HandleRemindTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleRemindTaskReply.ProtoReflect.Descriptor instead.
func (*HandleRemindTaskReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *HandleRemindTaskReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CreateLockerStorageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`          // 订单ID（必填，关联主订单）
	CabinetId     int64                  `protobuf:"varint,2,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`    // 柜子ID（必填，寄存的柜格编号）
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户ID（必填，寄存人ID）
	ExpireTime    int64                  `protobuf:"varint,4,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 过期时间（必填，秒级时间戳）
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                           // 寄存状态（必填，1=寄存中，0=待寄存）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLockerStorageRequest) Reset() {
	*x = CreateLockerStorageRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLockerStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLockerStorageRequest) ProtoMessage() {}

func (x *CreateLockerStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLockerStorageRequest.ProtoReflect.Descriptor instead.
func (*CreateLockerStorageRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *CreateLockerStorageRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateLockerStorageRequest) GetCabinetId() int64 {
	if x != nil {
		return x.CabinetId
	}
	return 0
}

func (x *CreateLockerStorageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateLockerStorageRequest) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *CreateLockerStorageRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateLockerStorageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         []*OrderInfo           `protobuf:"bytes,1,rep,name=order,proto3" json:"order,omitempty"` // 返回单个订单信息
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLockerStorageReply) Reset() {
	*x = CreateLockerStorageReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLockerStorageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLockerStorageReply) ProtoMessage() {}

func (x *CreateLockerStorageReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLockerStorageReply.ProtoReflect.Descriptor instead.
func (*CreateLockerStorageReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{9}
}

func (x *CreateLockerStorageReply) GetOrder() []*OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CreateLockerStorageReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ManageOrderSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNumber   string                 `protobuf:"bytes,1,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"` // 业务订单号（唯一标识）
	Title         string                 `protobuf:"bytes,12,opt,name=title,proto3" json:"title,omitempty"`
	OrderId       int64                  `protobuf:"varint,13,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        int64                  `protobuf:"varint,15,opt,name=status,proto3" json:"status,omitempty"`
	Role          int64                  `protobuf:"varint,19,opt,name=role,proto3" json:"role,omitempty"`
	Id            int64                  `protobuf:"varint,20,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageOrderSearchRequest) Reset() {
	*x = ManageOrderSearchRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageOrderSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageOrderSearchRequest) ProtoMessage() {}

func (x *ManageOrderSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageOrderSearchRequest.ProtoReflect.Descriptor instead.
func (*ManageOrderSearchRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{10}
}

func (x *ManageOrderSearchRequest) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *ManageOrderSearchRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ManageOrderSearchRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ManageOrderSearchRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ManageOrderSearchRequest) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *ManageOrderSearchRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ManageOrderSearchReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         []*OrderInfo           `protobuf:"bytes,1,rep,name=order,proto3" json:"order,omitempty"` // 返回单个订单信息
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageOrderSearchReply) Reset() {
	*x = ManageOrderSearchReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageOrderSearchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageOrderSearchReply) ProtoMessage() {}

func (x *ManageOrderSearchReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageOrderSearchReply.ProtoReflect.Descriptor instead.
func (*ManageOrderSearchReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{11}
}

func (x *ManageOrderSearchReply) GetOrder() []*OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *ManageOrderSearchReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 订单信息
type OrderInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                // 订单ID
	OrderNumber         string                 `protobuf:"bytes,2,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`                            // 业务订单号（唯一标识）
	UserId              int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                          // 用户ID（关联用户表）
	ScheduledDuration   int64                  `protobuf:"varint,6,opt,name=scheduled_duration,json=scheduledDuration,proto3" json:"scheduled_duration,omitempty"`         // 计划寄存时长（小时）
	ActualDuration      int64                  `protobuf:"varint,7,opt,name=actual_duration,json=actualDuration,proto3" json:"actual_duration,omitempty"`                  // 实际寄存时长（小时）
	Price               float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`                                                         // 基础费用
	Discount            float64                `protobuf:"fixed64,9,opt,name=discount,proto3" json:"discount,omitempty"`                                                   // 优惠金额
	AmountPaid          float64                `protobuf:"fixed64,10,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`                            // 实付金额
	StorageLocationName string                 `protobuf:"bytes,11,opt,name=storage_location_name,json=storageLocationName,proto3" json:"storage_location_name,omitempty"` // 寄存网点名称
	CabinetId           int64                  `protobuf:"varint,12,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`                                // 柜子ID
	Status              int64                  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`                                                       // 订单状态：1-待支付、2-寄存中、3-已完成、4-已取消、5-超时、6-异常
	DepositStatus       int64                  `protobuf:"varint,16,opt,name=deposit_status,json=depositStatus,proto3" json:"deposit_status,omitempty"`                    // 押金状态：1-已支付、2-已退还、3-已扣除
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{12}
}

func (x *OrderInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderInfo) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *OrderInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderInfo) GetScheduledDuration() int64 {
	if x != nil {
		return x.ScheduledDuration
	}
	return 0
}

func (x *OrderInfo) GetActualDuration() int64 {
	if x != nil {
		return x.ActualDuration
	}
	return 0
}

func (x *OrderInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderInfo) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *OrderInfo) GetAmountPaid() float64 {
	if x != nil {
		return x.AmountPaid
	}
	return 0
}

func (x *OrderInfo) GetStorageLocationName() string {
	if x != nil {
		return x.StorageLocationName
	}
	return ""
}

func (x *OrderInfo) GetCabinetId() int64 {
	if x != nil {
		return x.CabinetId
	}
	return 0
}

func (x *OrderInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderInfo) GetDepositStatus() int64 {
	if x != nil {
		return x.DepositStatus
	}
	return 0
}

// 创建订单请求
type CreateOrderRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OrderNumber         string                 `protobuf:"bytes,1,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`                           // 业务订单号（唯一标识）
	UserId              int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                         // 用户ID（关联用户表）
	ScheduledDuration   int64                  `protobuf:"varint,4,opt,name=scheduled_duration,json=scheduledDuration,proto3" json:"scheduled_duration,omitempty"`        // 计划寄存时长（小时）
	Price               float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`                                                        // 基础费用
	Discount            float64                `protobuf:"fixed64,6,opt,name=discount,proto3" json:"discount,omitempty"`                                                  // 优惠金额
	AmountPaid          float64                `protobuf:"fixed64,7,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`                            // 实付金额
	StorageLocationName string                 `protobuf:"bytes,8,opt,name=storage_location_name,json=storageLocationName,proto3" json:"storage_location_name,omitempty"` // 寄存网点名称
	CabinetId           int64                  `protobuf:"varint,9,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`                                // 柜子ID
	DepositStatus       int64                  `protobuf:"varint,10,opt,name=deposit_status,json=depositStatus,proto3" json:"deposit_status,omitempty"`                   // 押金状态：1-已支付、2-已退还、3-已扣除
	Title               string                 `protobuf:"bytes,12,opt,name=title,proto3" json:"title,omitempty"`
	OrderId             int64                  `protobuf:"varint,13,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status              int64                  `protobuf:"varint,15,opt,name=status,proto3" json:"status,omitempty"`
	HourlyRate          float32                `protobuf:"fixed32,16,opt,name=hourly_rate,json=hourlyRate,proto3" json:"hourly_rate,omitempty"`
	LockerPointId       int64                  `protobuf:"varint,17,opt,name=locker_point_id,json=lockerPointId,proto3" json:"locker_point_id,omitempty"`
	TypeId              int64                  `protobuf:"varint,18,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{13}
}

func (x *CreateOrderRequest) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *CreateOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetScheduledDuration() int64 {
	if x != nil {
		return x.ScheduledDuration
	}
	return 0
}

func (x *CreateOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateOrderRequest) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *CreateOrderRequest) GetAmountPaid() float64 {
	if x != nil {
		return x.AmountPaid
	}
	return 0
}

func (x *CreateOrderRequest) GetStorageLocationName() string {
	if x != nil {
		return x.StorageLocationName
	}
	return ""
}

func (x *CreateOrderRequest) GetCabinetId() int64 {
	if x != nil {
		return x.CabinetId
	}
	return 0
}

func (x *CreateOrderRequest) GetDepositStatus() int64 {
	if x != nil {
		return x.DepositStatus
	}
	return 0
}

func (x *CreateOrderRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateOrderRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateOrderRequest) GetHourlyRate() float32 {
	if x != nil {
		return x.HourlyRate
	}
	return 0
}

func (x *CreateOrderRequest) GetLockerPointId() int64 {
	if x != nil {
		return x.LockerPointId
	}
	return 0
}

func (x *CreateOrderRequest) GetTypeId() int64 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

type CreateOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"` // 支付链接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReply) Reset() {
	*x = CreateOrderReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReply) ProtoMessage() {}

func (x *CreateOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReply.ProtoReflect.Descriptor instead.
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{14}
}

func (x *CreateOrderReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 更新订单请求
type UpdateOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                               // 订单ID
	ActualDuration int64                  `protobuf:"varint,3,opt,name=actual_duration,json=actualDuration,proto3" json:"actual_duration,omitempty"` // 实际寄存时长（小时）
	Status         int64                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                                       // 订单状态
	DepositStatus  int64                  `protobuf:"varint,7,opt,name=deposit_status,json=depositStatus,proto3" json:"deposit_status,omitempty"`    // 押金状态
	HourlyRate     float32                `protobuf:"fixed32,8,opt,name=hourly_rate,json=hourlyRate,proto3" json:"hourly_rate,omitempty"`            //每小时费用
	LockerType     int64                  `protobuf:"varint,10,opt,name=locker_type,json=lockerType,proto3" json:"locker_type,omitempty"`
	Title          string                 `protobuf:"bytes,12,opt,name=title,proto3" json:"title,omitempty"`
	LockerPointId  int64                  `protobuf:"varint,17,opt,name=locker_point_id,json=lockerPointId,proto3" json:"locker_point_id,omitempty"`
	TypeId         int64                  `protobuf:"varint,18,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	CabinetId      int64                  `protobuf:"varint,19,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateOrderRequest) GetActualDuration() int64 {
	if x != nil {
		return x.ActualDuration
	}
	return 0
}

func (x *UpdateOrderRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateOrderRequest) GetDepositStatus() int64 {
	if x != nil {
		return x.DepositStatus
	}
	return 0
}

func (x *UpdateOrderRequest) GetHourlyRate() float32 {
	if x != nil {
		return x.HourlyRate
	}
	return 0
}

func (x *UpdateOrderRequest) GetLockerType() int64 {
	if x != nil {
		return x.LockerType
	}
	return 0
}

func (x *UpdateOrderRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateOrderRequest) GetLockerPointId() int64 {
	if x != nil {
		return x.LockerPointId
	}
	return 0
}

func (x *UpdateOrderRequest) GetTypeId() int64 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *UpdateOrderRequest) GetCabinetId() int64 {
	if x != nil {
		return x.CabinetId
	}
	return 0
}

type UpdateOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderInfo             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	PayUrl        string                 `protobuf:"bytes,2,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderReply) Reset() {
	*x = UpdateOrderReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderReply) ProtoMessage() {}

func (x *UpdateOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderReply.ProtoReflect.Descriptor instead.
func (*UpdateOrderReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateOrderReply) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *UpdateOrderReply) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

// 删除订单请求
type DeleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 订单ID
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderRequest) Reset() {
	*x = DeleteOrderRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRequest) ProtoMessage() {}

func (x *DeleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteOrderRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteOrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderReply) Reset() {
	*x = DeleteOrderReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderReply) ProtoMessage() {}

func (x *DeleteOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderReply.ProtoReflect.Descriptor instead.
func (*DeleteOrderReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteOrderReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取订单请求
type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 订单ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{19}
}

func (x *GetOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderInfo             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReply) Reset() {
	*x = GetOrderReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReply) ProtoMessage() {}

func (x *GetOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReply.ProtoReflect.Descriptor instead.
func (*GetOrderReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{20}
}

func (x *GetOrderReply) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

// 订单列表请求
type ListOrderRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Page                int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                                                           // 页码
	Size                int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`                                                           // 每页数量 	// 状态过滤
	StorageLocationName string                 `protobuf:"bytes,3,opt,name=storage_location_name,json=storageLocationName,proto3" json:"storage_location_name,omitempty"` // 寄存网点名称
	Status              string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListOrderRequest) Reset() {
	*x = ListOrderRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderRequest) ProtoMessage() {}

func (x *ListOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderRequest.ProtoReflect.Descriptor instead.
func (*ListOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{21}
}

func (x *ListOrderRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrderRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListOrderRequest) GetStorageLocationName() string {
	if x != nil {
		return x.StorageLocationName
	}
	return ""
}

func (x *ListOrderRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderInfo           `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"` // 订单列表 	// 总数量
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderReply) Reset() {
	*x = ListOrderReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderReply) ProtoMessage() {}

func (x *ListOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderReply.ProtoReflect.Descriptor instead.
func (*ListOrderReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{22}
}

func (x *ListOrderReply) GetOrders() []*OrderInfo {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrderReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ShowOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 页码// 每页数量 	// 状态过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowOrderRequest) Reset() {
	*x = ShowOrderRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowOrderRequest) ProtoMessage() {}

func (x *ShowOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowOrderRequest.ProtoReflect.Descriptor instead.
func (*ShowOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{23}
}

func (x *ShowOrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ShowOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         []*OrderInfo           `protobuf:"bytes,1,rep,name=order,proto3" json:"order,omitempty"` // 返回单个订单信息
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowOrderReply) Reset() {
	*x = ShowOrderReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowOrderReply) ProtoMessage() {}

func (x *ShowOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowOrderReply.ProtoReflect.Descriptor instead.
func (*ShowOrderReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{24}
}

func (x *ShowOrderReply) GetOrder() []*OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *ShowOrderReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_helloworld_v1_order_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/helloworld/v1/order.proto\x12\x11api.helloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\xbd\x02\n" +
	"\x18ManageOrderDetailRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x02 \x01(\x03R\tcabinetId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vexpire_time\x18\x04 \x01(\x03R\n" +
	"expireTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\x03R\x02id\x12!\n" +
	"\forder_number\x18\a \x01(\x03R\vorderNumber\x12-\n" +
	"\x12scheduled_duration\x18\b \x01(\x03R\x11scheduledDuration\x12\x1f\n" +
	"\vhourly_rate\x18\t \x01(\x03R\n" +
	"hourlyRate\x12\x12\n" +
	"\x04role\x18\n" +
	" \x01(\x03R\x04role\"^\n" +
	"\x16ManageOrderDetailReply\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\x122\n" +
	"\x05order\x18\x01 \x03(\v2\x1c.api.helloworld.v1.OrderInfoR\x05order\"\xba\x02\n" +
	"\x15ManageOrderDelRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x02 \x01(\x03R\tcabinetId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vexpire_time\x18\x04 \x01(\x03R\n" +
	"expireTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\x03R\x02id\x12!\n" +
	"\forder_number\x18\a \x01(\x03R\vorderNumber\x12-\n" +
	"\x12scheduled_duration\x18\b \x01(\x03R\x11scheduledDuration\x12\x1f\n" +
	"\vhourly_rate\x18\t \x01(\x03R\n" +
	"hourlyRate\x12\x12\n" +
	"\x04role\x18\n" +
	" \x01(\x03R\x04role\"'\n" +
	"\x13ManageOrderDelReply\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"\xa9\x02\n" +
	"\x18HandleTimeOutTaskRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x02 \x01(\x03R\tcabinetId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vexpire_time\x18\x04 \x01(\x03R\n" +
	"expireTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\x03R\x02id\x12!\n" +
	"\forder_number\x18\a \x01(\x03R\vorderNumber\x12-\n" +
	"\x12scheduled_duration\x18\b \x01(\x03R\x11scheduledDuration\x12\x1f\n" +
	"\vhourly_rate\x18\t \x01(\x03R\n" +
	"hourlyRate\"*\n" +
	"\x16HandleTimeOutTaskReply\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"\xd8\x01\n" +
	"\x17HandleRemindTaskRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x02 \x01(\x03R\tcabinetId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vexpire_time\x18\x04 \x01(\x03R\n" +
	"expireTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\x03R\x02id\x12!\n" +
	"\forder_number\x18\a \x01(\x03R\vorderNumber\")\n" +
	"\x15HandleRemindTaskReply\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"\xa8\x01\n" +
	"\x1aCreateLockerStorageRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x02 \x01(\x03R\tcabinetId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vexpire_time\x18\x04 \x01(\x03R\n" +
	"expireTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"`\n" +
	"\x18CreateLockerStorageReply\x122\n" +
	"\x05order\x18\x01 \x03(\v2\x1c.api.helloworld.v1.OrderInfoR\x05order\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"\xaa\x01\n" +
	"\x18ManageOrderSearchRequest\x12!\n" +
	"\forder_number\x18\x01 \x01(\tR\vorderNumber\x12\x14\n" +
	"\x05title\x18\f \x01(\tR\x05title\x12\x19\n" +
	"\border_id\x18\r \x01(\x03R\aorderId\x12\x16\n" +
	"\x06status\x18\x0f \x01(\x03R\x06status\x12\x12\n" +
	"\x04role\x18\x13 \x01(\x03R\x04role\x12\x0e\n" +
	"\x02Id\x18\x14 \x01(\x03R\x02Id\"^\n" +
	"\x16ManageOrderSearchReply\x122\n" +
	"\x05order\x18\x01 \x03(\v2\x1c.api.helloworld.v1.OrderInfoR\x05order\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"\x94\x03\n" +
	"\tOrderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\forder_number\x18\x02 \x01(\tR\vorderNumber\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12-\n" +
	"\x12scheduled_duration\x18\x06 \x01(\x03R\x11scheduledDuration\x12'\n" +
	"\x0factual_duration\x18\a \x01(\x03R\x0eactualDuration\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\x1a\n" +
	"\bdiscount\x18\t \x01(\x01R\bdiscount\x12\x1f\n" +
	"\vamount_paid\x18\n" +
	" \x01(\x01R\n" +
	"amountPaid\x122\n" +
	"\x15storage_location_name\x18\v \x01(\tR\x13storageLocationName\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\f \x01(\x03R\tcabinetId\x12\x16\n" +
	"\x06status\x18\r \x01(\x03R\x06status\x12%\n" +
	"\x0edeposit_status\x18\x10 \x01(\x03R\rdepositStatus\"\xf7\x03\n" +
	"\x12CreateOrderRequest\x12!\n" +
	"\forder_number\x18\x01 \x01(\tR\vorderNumber\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12-\n" +
	"\x12scheduled_duration\x18\x04 \x01(\x03R\x11scheduledDuration\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1a\n" +
	"\bdiscount\x18\x06 \x01(\x01R\bdiscount\x12\x1f\n" +
	"\vamount_paid\x18\a \x01(\x01R\n" +
	"amountPaid\x122\n" +
	"\x15storage_location_name\x18\b \x01(\tR\x13storageLocationName\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\t \x01(\x03R\tcabinetId\x12%\n" +
	"\x0edeposit_status\x18\n" +
	" \x01(\x03R\rdepositStatus\x12\x14\n" +
	"\x05title\x18\f \x01(\tR\x05title\x12\x19\n" +
	"\border_id\x18\r \x01(\x03R\aorderId\x12\x16\n" +
	"\x06status\x18\x0f \x01(\x03R\x06status\x12\x1f\n" +
	"\vhourly_rate\x18\x10 \x01(\x02R\n" +
	"hourlyRate\x12&\n" +
	"\x0flocker_point_id\x18\x11 \x01(\x03R\rlockerPointId\x12\x17\n" +
	"\atype_id\x18\x12 \x01(\x03R\x06typeId\"$\n" +
	"\x10CreateOrderReply\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"\xc4\x02\n" +
	"\x12UpdateOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x0factual_duration\x18\x03 \x01(\x03R\x0eactualDuration\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\x12%\n" +
	"\x0edeposit_status\x18\a \x01(\x03R\rdepositStatus\x12\x1f\n" +
	"\vhourly_rate\x18\b \x01(\x02R\n" +
	"hourlyRate\x12\x1f\n" +
	"\vlocker_type\x18\n" +
	" \x01(\x03R\n" +
	"lockerType\x12\x14\n" +
	"\x05title\x18\f \x01(\tR\x05title\x12&\n" +
	"\x0flocker_point_id\x18\x11 \x01(\x03R\rlockerPointId\x12\x17\n" +
	"\atype_id\x18\x12 \x01(\x03R\x06typeId\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x13 \x01(\x03R\tcabinetId\"_\n" +
	"\x10UpdateOrderReply\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.api.helloworld.v1.OrderInfoR\x05order\x12\x17\n" +
	"\apay_url\x18\x02 \x01(\tR\x06payUrl\"<\n" +
	"\x12DeleteOrderRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\",\n" +
	"\x10DeleteOrderReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"C\n" +
	"\rGetOrderReply\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.api.helloworld.v1.OrderInfoR\x05order\"\x86\x01\n" +
	"\x10ListOrderRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x122\n" +
	"\x15storage_location_name\x18\x03 \x01(\tR\x13storageLocationName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\\\n" +
	"\x0eListOrderReply\x124\n" +
	"\x06orders\x18\x01 \x03(\v2\x1c.api.helloworld.v1.OrderInfoR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\"\n" +
	"\x10ShowOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"V\n" +
	"\x0eShowOrderReply\x122\n" +
	"\x05order\x18\x01 \x03(\v2\x1c.api.helloworld.v1.OrderInfoR\x05order\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg2\x8c\r\n" +
	"\x05Order\x12v\n" +
	"\vCreateOrder\x12%.api.helloworld.v1.CreateOrderRequest\x1a#.api.helloworld.v1.CreateOrderReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/order/create\x12v\n" +
	"\vUpdateOrder\x12%.api.helloworld.v1.UpdateOrderRequest\x1a#.api.helloworld.v1.UpdateOrderReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/v1/order/update\x12s\n" +
	"\vDeleteOrder\x12%.api.helloworld.v1.DeleteOrderRequest\x1a#.api.helloworld.v1.DeleteOrderReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/order/del\x12g\n" +
	"\bGetOrder\x12\".api.helloworld.v1.GetOrderRequest\x1a .api.helloworld.v1.GetOrderReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/order/get\x12o\n" +
	"\tListOrder\x12#.api.helloworld.v1.ListOrderRequest\x1a!.api.helloworld.v1.ListOrderReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/orders/list\x12o\n" +
	"\tShowOrder\x12#.api.helloworld.v1.ShowOrderRequest\x1a!.api.helloworld.v1.ShowOrderReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/orders/show\x12\x94\x01\n" +
	"\x13CreateLockerStorage\x12-.api.helloworld.v1.CreateLockerStorageRequest\x1a+.api.helloworld.v1.CreateLockerStorageReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/create/locker/storage\x12\x88\x01\n" +
	"\x10HandleRemindTask\x12*.api.helloworld.v1.HandleRemindTaskRequest\x1a(.api.helloworld.v1.HandleRemindTaskReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/handle/remind/task\x12\x8c\x01\n" +
	"\x11HandleTimeOutTask\x12+.api.helloworld.v1.HandleTimeOutTaskRequest\x1a).api.helloworld.v1.HandleTimeOutTaskReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/handle/timeout/task\x12\x8d\x01\n" +
	"\x11ManageOrderSearch\x12+.api.helloworld.v1.ManageOrderSearchRequest\x1a).api.helloworld.v1.ManageOrderSearchReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/manage/orders/search\x12\x81\x01\n" +
	"\x0eManageOrderDel\x12(.api.helloworld.v1.ManageOrderDelRequest\x1a&.api.helloworld.v1.ManageOrderDelReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/manage/orders/del\x12~\n" +
	"\vManageOrder\x12(.api.helloworld.v1.ManageOrderDelRequest\x1a&.api.helloworld.v1.ManageOrderDelReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/manage/orders/del\x12\x8d\x01\n" +
	"\x11ManageOrderDetail\x12+.api.helloworld.v1.ManageOrderDetailRequest\x1a).api.helloworld.v1.ManageOrderDetailReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/manage/orders/detailB7\n" +
	"\x11api.helloworld.v1P\x01Z ito-deposit/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_order_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_order_proto_rawDescData []byte
)

func file_api_helloworld_v1_order_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_order_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_order_proto_rawDesc), len(file_api_helloworld_v1_order_proto_rawDesc)))
	})
	return file_api_helloworld_v1_order_proto_rawDescData
}

var file_api_helloworld_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_helloworld_v1_order_proto_goTypes = []any{
	(*ManageOrderDetailRequest)(nil),   // 0: api.helloworld.v1.ManageOrderDetailRequest
	(*ManageOrderDetailReply)(nil),     // 1: api.helloworld.v1.ManageOrderDetailReply
	(*ManageOrderDelRequest)(nil),      // 2: api.helloworld.v1.ManageOrderDelRequest
	(*ManageOrderDelReply)(nil),        // 3: api.helloworld.v1.ManageOrderDelReply
	(*HandleTimeOutTaskRequest)(nil),   // 4: api.helloworld.v1.HandleTimeOutTaskRequest
	(*HandleTimeOutTaskReply)(nil),     // 5: api.helloworld.v1.HandleTimeOutTaskReply
	(*HandleRemindTaskRequest)(nil),    // 6: api.helloworld.v1.HandleRemindTaskRequest
	(*HandleRemindTaskReply)(nil),      // 7: api.helloworld.v1.HandleRemindTaskReply
	(*CreateLockerStorageRequest)(nil), // 8: api.helloworld.v1.CreateLockerStorageRequest
	(*CreateLockerStorageReply)(nil),   // 9: api.helloworld.v1.CreateLockerStorageReply
	(*ManageOrderSearchRequest)(nil),   // 10: api.helloworld.v1.ManageOrderSearchRequest
	(*ManageOrderSearchReply)(nil),     // 11: api.helloworld.v1.ManageOrderSearchReply
	(*OrderInfo)(nil),                  // 12: api.helloworld.v1.OrderInfo
	(*CreateOrderRequest)(nil),         // 13: api.helloworld.v1.CreateOrderRequest
	(*CreateOrderReply)(nil),           // 14: api.helloworld.v1.CreateOrderReply
	(*UpdateOrderRequest)(nil),         // 15: api.helloworld.v1.UpdateOrderRequest
	(*UpdateOrderReply)(nil),           // 16: api.helloworld.v1.UpdateOrderReply
	(*DeleteOrderRequest)(nil),         // 17: api.helloworld.v1.DeleteOrderRequest
	(*DeleteOrderReply)(nil),           // 18: api.helloworld.v1.DeleteOrderReply
	(*GetOrderRequest)(nil),            // 19: api.helloworld.v1.GetOrderRequest
	(*GetOrderReply)(nil),              // 20: api.helloworld.v1.GetOrderReply
	(*ListOrderRequest)(nil),           // 21: api.helloworld.v1.ListOrderRequest
	(*ListOrderReply)(nil),             // 22: api.helloworld.v1.ListOrderReply
	(*ShowOrderRequest)(nil),           // 23: api.helloworld.v1.ShowOrderRequest
	(*ShowOrderReply)(nil),             // 24: api.helloworld.v1.ShowOrderReply
}
var file_api_helloworld_v1_order_proto_depIdxs = []int32{
	12, // 0: api.helloworld.v1.ManageOrderDetailReply.order:type_name -> api.helloworld.v1.OrderInfo
	12, // 1: api.helloworld.v1.CreateLockerStorageReply.order:type_name -> api.helloworld.v1.OrderInfo
	12, // 2: api.helloworld.v1.ManageOrderSearchReply.order:type_name -> api.helloworld.v1.OrderInfo
	12, // 3: api.helloworld.v1.UpdateOrderReply.order:type_name -> api.helloworld.v1.OrderInfo
	12, // 4: api.helloworld.v1.GetOrderReply.order:type_name -> api.helloworld.v1.OrderInfo
	12, // 5: api.helloworld.v1.ListOrderReply.orders:type_name -> api.helloworld.v1.OrderInfo
	12, // 6: api.helloworld.v1.ShowOrderReply.order:type_name -> api.helloworld.v1.OrderInfo
	13, // 7: api.helloworld.v1.Order.CreateOrder:input_type -> api.helloworld.v1.CreateOrderRequest
	15, // 8: api.helloworld.v1.Order.UpdateOrder:input_type -> api.helloworld.v1.UpdateOrderRequest
	17, // 9: api.helloworld.v1.Order.DeleteOrder:input_type -> api.helloworld.v1.DeleteOrderRequest
	19, // 10: api.helloworld.v1.Order.GetOrder:input_type -> api.helloworld.v1.GetOrderRequest
	21, // 11: api.helloworld.v1.Order.ListOrder:input_type -> api.helloworld.v1.ListOrderRequest
	23, // 12: api.helloworld.v1.Order.ShowOrder:input_type -> api.helloworld.v1.ShowOrderRequest
	8,  // 13: api.helloworld.v1.Order.CreateLockerStorage:input_type -> api.helloworld.v1.CreateLockerStorageRequest
	6,  // 14: api.helloworld.v1.Order.HandleRemindTask:input_type -> api.helloworld.v1.HandleRemindTaskRequest
	4,  // 15: api.helloworld.v1.Order.HandleTimeOutTask:input_type -> api.helloworld.v1.HandleTimeOutTaskRequest
	10, // 16: api.helloworld.v1.Order.ManageOrderSearch:input_type -> api.helloworld.v1.ManageOrderSearchRequest
	2,  // 17: api.helloworld.v1.Order.ManageOrderDel:input_type -> api.helloworld.v1.ManageOrderDelRequest
	2,  // 18: api.helloworld.v1.Order.ManageOrder:input_type -> api.helloworld.v1.ManageOrderDelRequest
	0,  // 19: api.helloworld.v1.Order.ManageOrderDetail:input_type -> api.helloworld.v1.ManageOrderDetailRequest
	14, // 20: api.helloworld.v1.Order.CreateOrder:output_type -> api.helloworld.v1.CreateOrderReply
	16, // 21: api.helloworld.v1.Order.UpdateOrder:output_type -> api.helloworld.v1.UpdateOrderReply
	18, // 22: api.helloworld.v1.Order.DeleteOrder:output_type -> api.helloworld.v1.DeleteOrderReply
	20, // 23: api.helloworld.v1.Order.GetOrder:output_type -> api.helloworld.v1.GetOrderReply
	22, // 24: api.helloworld.v1.Order.ListOrder:output_type -> api.helloworld.v1.ListOrderReply
	24, // 25: api.helloworld.v1.Order.ShowOrder:output_type -> api.helloworld.v1.ShowOrderReply
	9,  // 26: api.helloworld.v1.Order.CreateLockerStorage:output_type -> api.helloworld.v1.CreateLockerStorageReply
	7,  // 27: api.helloworld.v1.Order.HandleRemindTask:output_type -> api.helloworld.v1.HandleRemindTaskReply
	5,  // 28: api.helloworld.v1.Order.HandleTimeOutTask:output_type -> api.helloworld.v1.HandleTimeOutTaskReply
	11, // 29: api.helloworld.v1.Order.ManageOrderSearch:output_type -> api.helloworld.v1.ManageOrderSearchReply
	3,  // 30: api.helloworld.v1.Order.ManageOrderDel:output_type -> api.helloworld.v1.ManageOrderDelReply
	3,  // 31: api.helloworld.v1.Order.ManageOrder:output_type -> api.helloworld.v1.ManageOrderDelReply
	1,  // 32: api.helloworld.v1.Order.ManageOrderDetail:output_type -> api.helloworld.v1.ManageOrderDetailReply
	20, // [20:33] is the sub-list for method output_type
	7,  // [7:20] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_order_proto_init() }
func file_api_helloworld_v1_order_proto_init() {
	if File_api_helloworld_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_order_proto_rawDesc), len(file_api_helloworld_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_order_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_order_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_order_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_order_proto = out.File
	file_api_helloworld_v1_order_proto_goTypes = nil
	file_api_helloworld_v1_order_proto_depIdxs = nil
}
