// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: api/helloworld/v1/order.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{0}
}

type CreateOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReply) Reset() {
	*x = CreateOrderReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReply) ProtoMessage() {}

func (x *CreateOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReply.ProtoReflect.Descriptor instead.
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{1}
}

type UpdateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{2}
}

type UpdateOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderReply) Reset() {
	*x = UpdateOrderReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderReply) ProtoMessage() {}

func (x *UpdateOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderReply.ProtoReflect.Descriptor instead.
func (*UpdateOrderReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{3}
}

type DeleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderRequest) Reset() {
	*x = DeleteOrderRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRequest) ProtoMessage() {}

func (x *DeleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{4}
}

type DeleteOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderReply) Reset() {
	*x = DeleteOrderReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderReply) ProtoMessage() {}

func (x *DeleteOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderReply.ProtoReflect.Descriptor instead.
func (*DeleteOrderReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{5}
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{6}
}

type GetOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReply) Reset() {
	*x = GetOrderReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReply) ProtoMessage() {}

func (x *GetOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReply.ProtoReflect.Descriptor instead.
func (*GetOrderReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{7}
}

type ListOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderRequest) Reset() {
	*x = ListOrderRequest{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderRequest) ProtoMessage() {}

func (x *ListOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderRequest.ProtoReflect.Descriptor instead.
func (*ListOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{8}
}

type ListOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderReply) Reset() {
	*x = ListOrderReply{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderReply) ProtoMessage() {}

func (x *ListOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderReply.ProtoReflect.Descriptor instead.
func (*ListOrderReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{9}
}

var File_api_helloworld_v1_order_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/helloworld/v1/order.proto\x12\x11api.helloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\x14\n" +
	"\x12CreateOrderRequest\"\x12\n" +
	"\x10CreateOrderReply\"\x14\n" +
	"\x12UpdateOrderRequest\"\x12\n" +
	"\x10UpdateOrderReply\"\x14\n" +
	"\x12DeleteOrderRequest\"\x12\n" +
	"\x10DeleteOrderReply\"\x11\n" +
	"\x0fGetOrderRequest\"\x0f\n" +
	"\rGetOrderReply\"\x12\n" +
	"\x10ListOrderRequest\"\x10\n" +
	"\x0eListOrderReply2\xcf\x03\n" +
	"\x05Order\x12Y\n" +
	"\vCreateOrder\x12%.api.helloworld.v1.CreateOrderRequest\x1a#.api.helloworld.v1.CreateOrderReply\x12Y\n" +
	"\vUpdateOrder\x12%.api.helloworld.v1.UpdateOrderRequest\x1a#.api.helloworld.v1.UpdateOrderReply\x12Y\n" +
	"\vDeleteOrder\x12%.api.helloworld.v1.DeleteOrderRequest\x1a#.api.helloworld.v1.DeleteOrderReply\x12P\n" +
	"\bGetOrder\x12\".api.helloworld.v1.GetOrderRequest\x1a .api.helloworld.v1.GetOrderReply\x12c\n" +
	"\tListOrder\x12#.api.helloworld.v1.ListOrderRequest\x1a!.api.helloworld.v1.ListOrderReply\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/orderB7\n" +
	"\x11api.helloworld.v1P\x01Z ito-deposit/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_order_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_order_proto_rawDescData []byte
)

func file_api_helloworld_v1_order_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_order_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_order_proto_rawDesc), len(file_api_helloworld_v1_order_proto_rawDesc)))
	})
	return file_api_helloworld_v1_order_proto_rawDescData
}

var file_api_helloworld_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_helloworld_v1_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil), // 0: api.helloworld.v1.CreateOrderRequest
	(*CreateOrderReply)(nil),   // 1: api.helloworld.v1.CreateOrderReply
	(*UpdateOrderRequest)(nil), // 2: api.helloworld.v1.UpdateOrderRequest
	(*UpdateOrderReply)(nil),   // 3: api.helloworld.v1.UpdateOrderReply
	(*DeleteOrderRequest)(nil), // 4: api.helloworld.v1.DeleteOrderRequest
	(*DeleteOrderReply)(nil),   // 5: api.helloworld.v1.DeleteOrderReply
	(*GetOrderRequest)(nil),    // 6: api.helloworld.v1.GetOrderRequest
	(*GetOrderReply)(nil),      // 7: api.helloworld.v1.GetOrderReply
	(*ListOrderRequest)(nil),   // 8: api.helloworld.v1.ListOrderRequest
	(*ListOrderReply)(nil),     // 9: api.helloworld.v1.ListOrderReply
}
var file_api_helloworld_v1_order_proto_depIdxs = []int32{
	0, // 0: api.helloworld.v1.Order.CreateOrder:input_type -> api.helloworld.v1.CreateOrderRequest
	2, // 1: api.helloworld.v1.Order.UpdateOrder:input_type -> api.helloworld.v1.UpdateOrderRequest
	4, // 2: api.helloworld.v1.Order.DeleteOrder:input_type -> api.helloworld.v1.DeleteOrderRequest
	6, // 3: api.helloworld.v1.Order.GetOrder:input_type -> api.helloworld.v1.GetOrderRequest
	8, // 4: api.helloworld.v1.Order.ListOrder:input_type -> api.helloworld.v1.ListOrderRequest
	1, // 5: api.helloworld.v1.Order.CreateOrder:output_type -> api.helloworld.v1.CreateOrderReply
	3, // 6: api.helloworld.v1.Order.UpdateOrder:output_type -> api.helloworld.v1.UpdateOrderReply
	5, // 7: api.helloworld.v1.Order.DeleteOrder:output_type -> api.helloworld.v1.DeleteOrderReply
	7, // 8: api.helloworld.v1.Order.GetOrder:output_type -> api.helloworld.v1.GetOrderReply
	9, // 9: api.helloworld.v1.Order.ListOrder:output_type -> api.helloworld.v1.ListOrderReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_order_proto_init() }
func file_api_helloworld_v1_order_proto_init() {
	if File_api_helloworld_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_order_proto_rawDesc), len(file_api_helloworld_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_order_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_order_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_order_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_order_proto = out.File
	file_api_helloworld_v1_order_proto_goTypes = nil
	file_api_helloworld_v1_order_proto_depIdxs = nil
}
