name: ci
on:
  push:
    branches: [main]

env:
  REGISTRY: crpi-795sv9dwfov3lrnj.cn-shanghai.personal.cr.aliyuncs.com
  IMAGE_NAME: lanjinghexuan/ito-deposit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            docker stop ito-deposit || true
            docker rm ito-deposit || true
            docker run -d --restart=always \
              -p 8000:8000 -p 9005:9000 \
              -v /home/ito-deposit/configs:/data/conf \
              --name ito-deposit \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            
            # === 健康探针（TCP 端口 8000）===
            for i in {1..15}; do
            if nc -z 127.0.0.1 ${{ env.APP_PORT }}; then
            echo "✅ 端口 ${{ env.APP_PORT }} 已就绪，部署成功"
            exit 0
            fi
            sleep 3
            done
    
            echo "❌ 端口未就绪，开始回滚"
            docker stop ito-deposit && docker rm ito-deposit
            docker run -d --restart=always \
            -p 8000:8000 -p 9005:9000 \
            -v /home/ito-deposit/configs:/data/conf \
            --name ito-deposit \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-backup
            exit 1